// lib/qbTemplates.js
// Built-in exam designer templates. Each template defines a complete `design` object
// compatible with qbPdf.js. Teachers can also save their own via qb_templates table.

export const BUILTIN_TEMPLATES = {
  classic: {
    key: 'classic',
    name_ar: 'كلاسيكي',
    name_en: 'Classic',
    design: {
      page_size: 'a4',
      orientation: 'portrait',
      margin_mm: 18,
      font_family: 'Cairo',
      base_font_size: 12,
      question_spacing_mm: 8,
      line_spacing_mm: 6,
      question_numbering: '1,2,3...',
      section_numbering: 'roman',
      choice_layout: 'vertical',
      columns: 1,
      show_borders: true,
      border_color: '#001f43',
      watermark_text: '',
      watermark_opacity: 0.06,
      header_bg: '#001f43',
      header_fg: '#FFD700',
      section_bg: '#FFD700',
      section_fg: '#001f43',
      show_logo: true,
      logo_height_mm: 16,
    },
  },
  minimal: {
    key: 'minimal',
    name_ar: 'بسيط',
    name_en: 'Minimal',
    design: {
      page_size: 'a4',
      orientation: 'portrait',
      margin_mm: 22,
      font_family: 'Cairo',
      base_font_size: 11,
      question_spacing_mm: 6,
      line_spacing_mm: 5,
      question_numbering: '1,2,3...',
      section_numbering: 'alpha',
      choice_layout: 'vertical',
      columns: 1,
      show_borders: false,
      border_color: '#888888',
      watermark_text: '',
      watermark_opacity: 0.04,
      header_bg: '#ffffff',
      header_fg: '#001f43',
      section_bg: '#f1f1f1',
      section_fg: '#001f43',
      show_logo: false,
      logo_height_mm: 0,
    },
  },
  school: {
    key: 'school',
    name_ar: 'مدرسي',
    name_en: 'School',
    design: {
      page_size: 'a4',
      orientation: 'portrait',
      margin_mm: 16,
      font_family: 'Cairo',
      base_font_size: 12,
      question_spacing_mm: 7,
      line_spacing_mm: 6,
      question_numbering: '1,2,3...',
      section_numbering: 'roman',
      choice_layout: 'vertical',
      columns: 1,
      show_borders: true,
      border_color: '#001f43',
      watermark_text: '',
      watermark_opacity: 0.05,
      header_bg: '#001f43',
      header_fg: '#FFD700',
      section_bg: '#1f3a60',
      section_fg: '#FFD700',
      show_logo: true,
      logo_height_mm: 18,
    },
  },
  modern: {
    key: 'modern',
    name_ar: 'عصري',
    name_en: 'Modern',
    design: {
      page_size: 'a4',
      orientation: 'portrait',
      margin_mm: 20,
      font_family: 'Cairo',
      base_font_size: 12,
      question_spacing_mm: 9,
      line_spacing_mm: 6,
      question_numbering: 'circle',
      section_numbering: 'alpha',
      choice_layout: 'horizontal_2col',
      columns: 1,
      show_borders: false,
      border_color: '#00E5FF',
      watermark_text: '',
      watermark_opacity: 0.04,
      header_bg: '#00E5FF',
      header_fg: '#001f43',
      section_bg: '#00E5FF',
      section_fg: '#001f43',
      show_logo: true,
      logo_height_mm: 14,
    },
  },
  compact: {
    key: 'compact',
    name_ar: 'مضغوط',
    name_en: 'Compact',
    design: {
      page_size: 'a4',
      orientation: 'portrait',
      margin_mm: 12,
      font_family: 'Cairo',
      base_font_size: 10,
      question_spacing_mm: 4,
      line_spacing_mm: 4,
      question_numbering: '1,2,3...',
      section_numbering: 'alpha',
      choice_layout: 'horizontal_2col',
      columns: 2,
      show_borders: true,
      border_color: '#888888',
      watermark_text: '',
      watermark_opacity: 0.03,
      header_bg: '#001f43',
      header_fg: '#FFD700',
      section_bg: '#FFD700',
      section_fg: '#001f43',
      show_logo: false,
      logo_height_mm: 0,
    },
  },
}

export const DEFAULT_TEMPLATE_KEY = 'classic'

export function getTemplateDesign(key) {
  return (BUILTIN_TEMPLATES[key] || BUILTIN_TEMPLATES[DEFAULT_TEMPLATE_KEY]).design
}

export function listBuiltinTemplates(isArabic = true) {
  return Object.values(BUILTIN_TEMPLATES).map((t) => ({
    key: t.key,
    name: isArabic ? t.name_ar : t.name_en,
    design: t.design,
  }))
}
